##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.10.0-B14] date: [Tue Oct 20 17:51:11 MSK 2020] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = Firmware


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Src/main.c \
Src/systick.c \
Src/gd32e10x_it.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_adc.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_bkp.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_can.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_crc.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_ctc.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_dac.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_dbg.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_dma.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_exmc.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_exti.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_fmc.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_fwdgt.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_gpio.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_i2c.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_misc.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_pmu.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_rcu.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_rtc.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_spi.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_timer.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_usart.c \
Drivers/GD32E10x_standard_peripheral/Source/gd32e10x_wwdgt.c \
Drivers/CMSIS/GD/GD32E10x/Source/system_gd32e10x.c

# ASM sources
ASM_SOURCES = startup_gd32e10x.s

#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS = \
-DGD32E10X \
-DHXTAL_VALUE=8000000U \
-DHXTAL_VALUE_8M=8000000U

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES = \
-IInc \
-IDriversExt \
-IDrivers/GD32E10x_standard_peripheral/Include \
-IDrivers/CMSIS/GD/GD32E10x/Include \
-IDrivers/CMSIS


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif

# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"

#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = GD32E103C8TX_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR)
	@echo $<
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	@echo $<
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@
	
$(BUILD_DIR):
	mkdir $@

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)

#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
